version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "80:9000"
      - "443:443"
    links:
      - db:db
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    ports: 
      - 3306:3306
    environment:       
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ../mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d